import Logo from "./Components/Logo";
import Navigation from "./Components/Navigation";

export const metadata = {
	title: "The Wild Oasis",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<header>
					<Logo />
					<Navigation />
				</header>
				<main>{children}</main>
				<footer>Copy right by the wild oasis</footer>
			</body>
		</html>
	);
}
